; Seperate section for Aircraft Transports' Addition. Injected into Rulesmd.

; This addition aims to replicate Generals style of Aircraft Transport hover up and down for transporting.
; Requirement: Phobos (Must have), Ares (Must have).

; Instruction:
; - Set the original unit TechLevel to -1. The original should be only be used by AI.
; - Define additional unit that mirrors the original one. In the unit's code, it should
; have $Inherit= ORIGINALUNITNAME, JJTEM. In case of further modification, JJTEM should
; always be defined last in the list.
; - Do not forget to carry the images of original one too.
; - Assign jumpjet armor with custom ones. They are needed to maintain functionality with
; Autofire. By default all designated JJ should have jumpjetTLArmor assigned.
; - Assign true weapon into Secondaries. Those Seconadries weapon should be assigned with
; $Inherits=AmmoHackWeapon. There can be only one "true" weapon per Technotype that uses
; this mechanic.
; - Be sure that the new JJ should be reverted to old JJ when under AI's hand and vice versa.

; /// CUSTOM ARMORTYPE ///
[ArmorTypes]
jumpjetTLArmor=light
jumpjetTMArmor=medium
jumpjetTHArmor=heavy

; /// TECHNOTYPE ///
[VehicleTypes]
SHAD1=SHADNEW

; Override Tech Level of original SHAD to be unbuildable by the players
; Computer-only SHAD. Behaves like vanilla.
[SHAD]
TechLevel=-1
; *** PHOBOS FEATURE ***
; Revert to Player-only version if under Player control
Convert.ComputerToHuman=SHADNEW    ; TechnoType
; New player-only SHAD. Always float in the air.
; SHAD1 deploys to SHAD2 by using deploy order, or being affected by convert warhead
[SHADNEW]
Image=SHAD
$Inherits=SHAD
TechLevel=7
; Where true weapons shoot
Secondary=BlackHawkCannon
EliteSecondary=BlackHawkCannonE
; *** ARES FEATURES ***
; 100% Survivability rate
Survivor.RookiePassengerChance=100%
Survivor.VeteranPassengerChance=100%
Survivor.ElitePassengerChance=100%
; *** PHOBOS FEATURES ***
; Revert to Computer only version if under Computer control
Convert.HumanToComputer=SHAD    ; TechnoType
; Ignore passenger queue on transport
NoQueueUpToEnter=yes         ; boolean, default to [General] -> NoQueueUpToEnter
NoQueueUpToUnload=yes        ; boolean, default to [General] -> NoQueueUpToUnload
; Jumpjet Tilt
JumpjetTilt=yes                       ; boolean
JumpjetTilt.ForwardAccelFactor=1.0      ; floating point value
JumpjetTilt.ForwardSpeedFactor=1.0      ; floating point value
JumpjetTilt.SidewaysRotationFactor=1.0  ; floating point value
JumpjetTilt.SidewaysSpeedFactor=1.0     ; floating point value

; *** NEW JUMPJET MECHANIC SECTION ***
; Dummy Primary weapon to keep the aircraft flying!
Primary=JumpjetTTarget
ElitePrimary=JumpjetTTarget
; Custom armor for Autofire mechanic
Armor=jumpjetTLArmor
; DO NOT DISABLE THEM. THEY ARE REQUIRED FOR THE JJ TO STAY AFLOAT
OpportunityFire=yes
CanPassiveAquire=yes ; WILL try to pick up own targets
; FireWhileMoving=no
; ALSO REQUIRED FOR THE JJ TO STAY AFLOAT
AutoFire=yes             ; boolean
AutoFire.TargetSelf=yes  ; boolean ; In which case the normal targeting system takes effect
; Ammo mechanic for land delay. Was in JumpjetTTarget's ROF.
; If JumpjetTTarget has too much ROF, Secondary will not fire after killing off the first one.
; Ammo is there 
Ammo=1
Reload=99999999 ; Approx delays of which it will fire again. Defaults to extremely long time
; Setting Guard mechanic for proper landing
GuardRange=1 
DefaultToGuardArea=yes
; Custom Cursor Feature
Cursor.NoMove=Enter
Cursor.NoDeploy=NoDeploy

; /// WEAPONS ///
; Timer of which it will flies again!
[JumpjetTTimer] ; Was using its max ROF. See above.
ROF=40 
; Why the maximum ROF? It's to make sure it's stay on the ground as long as it possibly can
; The acceptable duration ranges from the smallest ROF to 32767 (Max)
; Dummy weapon for keeping the JJ in the air!
[JumpjetTTarget] 
$Inherits=JumpjetTBase,JumpjetTTimer
Projectile=JumpjetTGProj
Warhead=TargetWH
OmniFire=yes
FireWhileMoving=no
Ammo=0
; *** PHOBOS FEATURES ***
; Custom targeting
CanTarget=empty; List of Affected Target Enumeration (none|land|water|empty|infantry|units|buildings|all)
; Base JJ Transport weapon
[JumpjetTBase]
Damage=1
Range=0
Speed=100
AllowZeroDamage=yes
; For ammo hacks!
[AmmoHackWeapon]
Ammo=0
; The weapons Designated JJs is currently using
[BlackHawkCannon]
$Inherits=AmmoHackWeapon
[BlackHawkCannonE]
$Inherits=AmmoHackWeapon

; /// WARHEAD ///
[Warhead]
JumpjetTWH0=TargetWH
; Serves for targeting purposes
[TargetWH]
AnimList=CARYLAND,CARYLAND
Verses=0%,0%,0%,0%,0%,0%,0%,0%,0%,0%,0%
Versus.jumpjetTArmor=2%
AffectsOwner=no
AffectsAllies=no
AffectsEnemies=no
Nonprovocative=true

; /// PROJECTILE ///
; Jumpjet Projectile. Only targets on ground.
[JumpjetTGProj]
Inviso=yes
Image=none
AA=no
AG=yes
