; Seperate section for Projectiles. Injected into Rulesmd.

; **************************************************************************
; ************************** Projectiles ***********************************
; **************************************************************************

; ******* Projectile Statistics *******
; Projectiles describe how and what image to use as the weapon flies
; to its target. Think of the projectile as the "delivery method" used
; to get the warhead to the desired target.

; AA = Can this weapon fire upon flying aircraft (def=no)?
; AG = Can this weapon fire upon ground objects (def=yes)?
; AN = Can this weapon fire upon naval objects (def=yes)?
; AS = Can this weapon fire upon sub-marine objects (def=no)?
; ASW = Is this an Anti-Submarine-Warfare projectile (def=no)?
; Acceleration = amount to increase missile speed (def=3)
; Airburst = Does it try to fly over the target instead of hit it (def=no)?
; Arcing = Does the bullet travel using an arcing path rather than a straight line? (def=no)
; Arm = arming delay (def=0)
; Bouncy = Does it bounce a bit upon impact (def=no)?
; Cluster = number of explosions attached to projectile [cluster-bomb] (def=1)
; Color = Color  to use for special remapping projectiles (def = none)
; CourseLockDuration = How many frames the projectile keep its initial course locked for. (def=0)
; Degenerates = Does the bullet strength weaken as it travels (def=no)?
; Dropping = Does it fall from a starting height (def=no)?
; Level = Does it stay at the same altitude in flight? (Currently also acts as IsTorpedo)
; Elasticity = "bounciness" of the object [should be 0.0 through 1.0] (def=0.75)
; Image = image to use during flight
; Inaccurate = Is it inherently inaccurate (def=no)?
; Inviso = Is the projectile invisible as it travels (def=no)?
; Parachuted = Equipped with a parachute for dropping from plane (def=no)?
; Proximity = Does it blow up when near its target (def=no)?
; ROT = Rate Of Turn [non zero implies homing] (def=0)
; Ranged = Can it run out of fuel (def=no)?
; Scalable = Can its animations be tuned up and down on the fly? (def=no)
; Shadow = If High, does this bullet need to have a shadow drawn? (def = yes)
; SubjectToCliffs = Can this bullet be stopped by upward cliffs?  No effect on homing projectiles. (def=no)
; SubjectToElevation = Can this bullet get a range bonus from height?  No effect on homing projectiles.  (def=no)
; SubjectToWalls = Can this bullet be stopped by walls?  (def=no)
; VeryHigh = Does it fly at a very high cruise altitude (def=no)?



; invisible flight to target
[Invisible]
Inviso=yes
Image=none

; Harpy Claw tracking projectile
[Invisible2]
Inviso=yes
Image=none
ROT=3
AA=yes
AG=yes

; Jump jet cannon
[Invisible3]
Inviso=yes
Image=none
AA=yes
AG=yes


[Invisible4]
Inviso=yes
Image=none
AA=yes
AG=no

[Invisible5]
Inviso=yes
Image=none
AA=no
AG=no
;AN=yes

[InvisibleVertical]
Inviso=yes
Image=none
Vertical=yes

; PCG; Use this for weapons that are invisble but are subject to cliffs, elevation and walls.
[InvisibleLow]
Inviso=yes
Image=none
SubjectToCliffs=yes
SubjectToElevation=yes
SubjectToWalls=yes

; PCG; Use this for weapons that are invisble but are subject to cliffs, elevation and walls.
[InvisibleMedium]
Inviso=yes
Image=none
SubjectToCliffs=yes
SubjectToElevation=yes
SubjectToWalls=no

; PCG; Use this for weapons that can fire over walls and up cliffs.
[InvisibleHigh]
Inviso=yes
Image=none
SubjectToElevation=yes

; Invisible All Purpose
[InvisibleAll] ; used by all the things with infinite range (-2) so do not let it be SubjectTo Anything
Inviso=yes
Image=none
AA=yes
AG=yes
;AN=yes
;AS=yes

; Used by mind control
[PsychicControl]
;Image=YURBLANK ; an invisible missile with a trailer
;ROT=100
Inviso=yes
Image=none
;Shadow=no
;Proximity=yes
;Ranged=yes

[Psychic]
Inviso=yes
Image=none

; APC Quad Cannon shells
[QuadShell]
Inviso=yes
Image=none
AA=yes ;no
AG=yes
SubjectToElevation=no
SubjectToCliffs=no
SubjectToWalls=no

[Null]
Inviso=yes
Arm=9999999
Image=none

; straight high-speed ballistic shot
[Cannon]
Image=120MM
Arcing=true
SubjectToCliffs=yes
SubjectToElevation=yes
SubjectToWalls=yes

; orca bomber bomblets
[Cannon2]
Image=120MM
AA=no

; chemical missile
[ChemMissile]
Arm=2
VeryHigh=yes
Cluster=8
;Shadow=no
Proximity=yes
Ranged=yes
AA=no
Image=MISLCHEM
ROT=4
Color=DarkGreen
IgnoresFirestorm=yes

[V3AirburstP] ;this is transition between unit rocket and little missiles
Proximity=yes
Dropping=yes
Cluster=9
Image=none
Airburst=yes
AirburstWeapon=V3Cluster
Ranged=yes
AA=no
ROT=4

[JUMP]
Image=DRONP ;Hmm...Requires an Image entry to get at Rotates=.  Violates the same name default rule
AA=no
Arm=2
ROT=8 ;requires to use Rotates
Shadow=no
Proximity=yes
Ranged=yes
FirersPalette=yes ; Borrows the convertClass from the firing unit - gets house color too
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=yes

[DOGJUMP]
Image=DOGP ;Hmm...Requires an Image entry to get at Rotates=.  Violates the same name default rule
AA=no
;AN=no
Arm=2
ROT=8 ;requires to use Rotates
Shadow=no
Proximity=yes
Ranged=yes
FirersPalette=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=yes

[ADOGJUMP]
Image=ADOGP ;Hmm...Requires an Image entry to get at Rotates=.  Violates the same name default rule
AA=no
;AN=no
Arm=2
ROT=8 ;requires to use Rotates
Shadow=no
Proximity=yes
Ranged=yes
FirersPalette=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=yes

[SQDJUMP]
;Image=SQDP ;Hmm...Requires an Image entry to get at Rotates=.  Violates the same name default rule
Inviso=yes ;### temp
Image=none ;### temp
AA=no
;AN=yes
;AS=yes ; tricky.  Needed to attack a sub, the non organic underwater guy, but Anti Organic will override for Dolphins
Arm=2
ROT=8 ;requires to use Rotates
Shadow=no
Proximity=yes
Ranged=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=yes

[GiantNukeUp]
Arm=2
Shadow=no
Image=NKMSLUP
Acceleration=1
Vertical=yes ; Not a missile or a projectile.  Just go up until...
DetonationAltitude=20000; All this does is create the downward pointing one over the target
FirersPalette=yes

[GiantNukeDown]
Arm=2
Shadow=no
Image=NKMSLDN
Acceleration=1
Vertical=yes ; //like blimp bomb
DetonationAltitude=30000;
FirersPalette=yes

; small homing missile (targets vehicles best)
[HeatSeeker]
Arm=2
Shadow=no
Proximity=yes
Ranged=yes
Image=DRAGON
ROT=8
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no

; Basic Torpedo for Subs
[Torpedo]
Arm=2
Shadow=no
;Proximity=yes
Ranged=yes
Image=SUBT
ROT=12 ;4
AA=no
;AN=yes
AG=yes
;AS=yes
Level=yes

; virtual projectile for dolphin sonic attack
[Sonic]
;AG=no ;gs New naval targeting makes this unneeded, and it is knida wrong in theory anyway (ground and water are confused enough without this one's help)
;AS=yes
Level=yes

; virtual projectile for destroyer helicoptor attack
[ASWVirt]
AG=no
;AS=yes
AA=no
;AN=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no

[ClusterBits]
Arm=2
Shadow=no
Proximity=yes
Ranged=yes
Image=DRAGON
ROT=60

[ProtonTorpedo]
Arm=2
Shadow=no
Proximity=yes
Ranged=yes
Image=TORPEDO
ROT=1
IgnoresFirestorm=yes

[NormalBomb]
Arm=2
Shadow=no
Proximity=yes
Ranged=yes
Image=DRAGON
ROT=1
IgnoresFirestorm=yes

[BlimpBombP]
Image=ZBOMB
Arm=10
Shadow=no
Acceleration=1
Vertical=yes ;can't turn or do much of anything.  Just stays on the vector of its initial shooting (up or down)
DetonationAltitude=20000 ; Needs this to prevent premature explosionation since uses same system as nuke

[BlimpBombPE]
ShrapnelWeapon=SuperCometFragment
ShrapnelCount=8
Image=ZBOMB
Arm=10
Shadow=no
Acceleration=1
Vertical=yes ;can't turn or do much of anything.  Just stays on the vector of its initial shooting (up or down)
DetonationAltitude=20000 ; Needs this to prevent premature explosionation since uses same system as nuke


[DepthCharge]
Arm=2
Shadow=no
Proximity=yes
Ranged=yes
Image=DRAGON
ROT=1
IgnoresFirestorm=yes
;AS=yes

[ProtonBlast]
Shadow=no
Proximity=yes
Ranged=yes
Image=TORPEDO
ROT=1
IgnoresFirestorm=yes

; aircraft-only heatseeker
[AAHeatSeeker]
Arm=2
Shadow=no
Proximity=yes
Ranged=yes
AA=yes
AG=no
;AN=no
Image=DRAGON
ROT=80 ;10
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no

; aircraft and ground heatseeker
[AAHeatSeeker2]
Arm=2
Shadow=no
;Proximity=yes
Proximity=no
Ranged=yes
AA=yes
AG=yes
Image=DRAGON
ROT=60
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no

; aircraft and ground heatseeker
[AirToGroundMissile]
Arm=2
Shadow=no
;Proximity=yes
Proximity=no
Ranged=yes
AA=no
AG=yes
Image=DRAGON
ROT=100 ;was 60
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no

[AAHeatSeeker3]
Arm=2
Shadow=no
Proximity=yes
Ranged=yes
AA=yes
AG=yes
Image=DRAGON
ROT=16
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=yes

; aircraft and ground heatseeker
[NavalToGroundSeeker]
Arm=2
Shadow=no
;Proximity=yes
Proximity=no
Ranged=yes
AG=yes
AN=no
Image=DRAGON
ROT=60
Acceleration=1
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no

[DredMissile]
Arm=2
Shadow=no
Proximity=yes
Ranged=yes
AG=yes
Image=DREDMISS
ROT=16
FirersPalette=yes ; Take the palette from the thing that shot you (art thing)

; Aircraft-only heatseeker for the Aegis
[MedusaProjectile]
Arm=1
High=yes
Shadow=no
AA=yes
AG=no
;AN=no
Image=MEDUSA
CourseLockDuration=15
ROT=20
Scalable=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no

[Lobbed]
Image=DISCUS
Bouncy=yes
Arcing=yes
Floater=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no

[Lobbed2]
High=yes
Image=CANISTER
Arcing=true
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no

; arcing ballistic projectile
[Ballistic]
Image=120MM
Arcing=true
SubjectToCliffs=no
SubjectToElevation=yes
SubjectToWalls=no

[PulsPr]
Image=PULSBALL

[LLine]
Inviso=yes
Image=none
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no

[LLine2]
Inviso=yes
Image=none
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no

[DogShard]
Image=CRYSTAL4
Arcing=true

[GrandCannonBall]
Level=no
Image=120MM		; put in new art for this
Arcing=true
SubjectToCliffs=no
SubjectToElevation=yes
SubjectToWalls=no

[FlakProj]		; AA bullet for Flak Cannon and Flak Track.
Image=none
Inviso=yes
AA=yes
AG=no
;AN=no
Shadow=no
Ranged=yes		; Not homing, but ranged -- check fuse, explode if near target coords
Inaccurate=yes	; Bullets do not snap onto targets when "close enough".
FlakScatter=yes ; This weapon scatters its shots.
SubjectToCliffs=no
SubjectToElevation=yes
SubjectToWalls=no

[FlakTProj]		; Anti-surface bullet for Flak Track.
Image=120MM
Arcing=true
Inviso=no
AA=no
AG=yes
;AN=yes
Shadow=no
Inaccurate=yes	; Bullets do not snap onto targets when "close enough".
FlakScatter=yes ; This weapon scatters its shots.
SubjectToCliffs=no
SubjectToElevation=yes
SubjectToWalls=yes

[Electricbounce]
ShrapnelWeapon=TeslaFragment
ShrapnelCount=2
Inviso=yes
Image=none
SubjectToCliffs=yes
SubjectToElevation=no
SubjectToWalls=no

[SuperCometP]
ShrapnelWeapon=SuperCometFragment
ShrapnelCount=5 ; Means (10 - (Range in cells))
Inviso=yes
Image=none
SubjectToCliffs=yes
SubjectToElevation=no
SubjectToWalls=no

[SuperSmallCometP]
ShrapnelWeapon=CometFragment
ShrapnelCount=3 ; Non neg means absolutely 3
Inviso=yes
Image=none
SubjectToCliffs=yes
SubjectToElevation=no
SubjectToWalls=no

[LargeCometP]
ShrapnelWeapon=CometFragment
;ShrapnelCount=-10
ShrapnelCount=5
Inviso=yes
Image=none
SubjectToCliffs=yes
SubjectToElevation=no
SubjectToWalls=no

[SmallCometP]
Inviso=yes
Image=none
SubjectToCliffs=yes
SubjectToElevation=yes
SubjectToWalls=yes

[SmallTeslaP]
Inviso=yes
Image=none
SubjectToCliffs=yes
SubjectToElevation=yes
SubjectToWalls=yes

