
; RULE*.INI
; *** Red Alert 2: Yuri's Revenge Rules ***
; If placed in game directory, it will override built in values. Values to be used as multipliers
; or percentages can be specified as either a simple floating point number (embed ".") or as a
; conventional percentage number (append "%"). Values used as distances or time delays
; are specified as simple floating point number. Distance values are expressed in cells. Time
; values are expressed in minutes.
; If multiple rules files are present, the Name field is used to identify between them.

; Remember to drag this into expandmd03.mix after edit

[General]
UIName=Name:General
Name=Red Alert 2 Yuri's Revenge -- Official Rules of Engagement

;[$Include] section contains a list of files to read and include. Files can be directly in the Red Alert 2 directory or in a loaded MIX file.
;Files will be added in the same order they are defined. Index of each file must be unique among all included files.
;Inclusion can be nested recursively (included files can include files further). Recursion is depth-first (before including next file, check if the current one includes anything).
;When the same entry exists in two files, then the one read later will overwrite the value.
;This feature can be used in any INI file, be it rulesmd.ini, artmd.ini, soundmd.ini, map file or anything else.

;All the vital stats and definitions get included first. Put your additional game features below them!

[$Include]
; General section of the rules
0=INI\Rules Code\rules_general.ini
; Buildable units
1=INI\Rules Code\rules_infantry.ini
2=INI\Rules Code\rules_vehicles.ini
3=INI\Rules Code\rules_aircrafts.ini
4=INI\Rules Code\rules_buildings.ini
; Neutral units
5=INI\Rules Code\rules_civ.ini
6=INI\Rules Code\rules_civ_vehicles.ini
7=INI\Rules Code\rules_civ_buildings.ini
8=INI\Rules Code\rules_civ_aircrafts.ini
; Weapons, warheads and projectiles
9=INI\Rules Code\rules_weapons.ini
10=INI\Rules Code\rules_elite_weapons.ini
11=INI\Rules Code\rules_warhead.ini
12=INI\Rules Code\rules_projectiles.ini
; Terrain and Overlays
13=INI\Rules Code\rules_terrain.ini
; Special Weapons and Super Weapons
14=INI\Rules Code\rules_sw.ini
; Particles
14=INI\Rules Code\rules_particles.ini
; Miscellaneous
15=INI\Rules Code\rules_misc.ini

; **********************************************
; ***************** CHANGE LOG *****************
; **********************************************

; I know a dumbass who DID NOT write change log, or bother to remember what changed.

; ************** Changelog 0.1 *****************

; - Seperated the file into multiple sections. Located at the Rules Code subfolder in the INI folder of the mod directory.
; - Added JJ Transport improvement.
