; Seperate section for Elite Weapons. Injected into Rulesmd.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;ELITE WEAPONS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; rapid fire anti-ground machine gun
[AGGattlingE]
Damage=25
ROF=16
Range=6
Projectile=Invisiblelow ;GEF Anti ground ;SA
Speed=100
Warhead=GattWH
Report=GattlingGunAttackLoop1
;DownReport=GattlingGunDecreaseLoop1
Burst = 2
Anim=MGUN-N,MGUN-NE,MGUN-E,MGUN-SE,MGUN-S,MGUN-SW,MGUN-W,MGUN-NW

; rapid fire anti-air machine gun
[AAGattlingE]
Damage=25
ROF=16
Range=8
Projectile=Invisible4 ;GEF Anti air ;SA
Speed=100
Warhead=GattWH
Report=GattlingGunAttackLoop1
;DownReport=GattlingGunDecreaseLoop1
Burst = 2
Anim=MGUN-N,MGUN-NE,MGUN-E,MGUN-SE,MGUN-S,MGUN-SW,MGUN-W,MGUN-NW

; rapid fire anti-ground machine gun
[AGGattling2E]
Damage=25
ROF=16
Range=6
Projectile=Invisiblelow ;GEF Anti ground ;SA
Speed=100
Warhead=SA
Report=GattlingGunAttackLoop2
;DownReport=GattlingGunDecreaseLoop2
Anim=GUNFIRE
Burst = 2

; rapid fire anti-air machine gun
[AAGattling2E]
Damage=25
ROF=8
Range=8
Projectile=Invisible4 ;GEF Anti air ;SA
Speed=100
Warhead=GattWH
Report=GattlingGunAttackLoop2
;DownReport=GattlingGunDecreaseLoop2
Anim=GUNFIRE
Burst = 2

; rapid fire anti-ground machine gun
[AGGattling3E]
Damage=25
ROF=16
Range=6
Projectile=Invisiblelow ;GEF Anti ground ;SA
Speed=100
Warhead=SSA
Report=GattlingGunAttackLoop3
;DownReport=GattlingGunDecreaseLoop3
Anim=VTMUZZLE
Burst = 2

; rapid fire anti-air machine gun
[AAGattling3E]
Damage=25
ROF=4
Range=8
Projectile=Invisible4 ;GEF Anti air ;SA
Speed=100
Warhead=GattWH
Report=GattlingGunAttackLoop3
;DownReport=GattlingGunDecreaseLoop3
Anim=VTMUZZLE
Burst = 2

[M1CarbineE]
Damage=20
ROF=25
Range=5
Projectile=InvisibleLow
Speed=100
Warhead=SA
Report=ConscriptAttack
OccupantAnim=UCCONS

[PsychicJabE]
Damage=30
ROF=15
Range=6
Projectile=InvisibleLow
Speed=100
Warhead=SAFlame
Report=InitiateAttack
OccupantAnim=UCINIT
OpenToppedAnim=GUNFIRE;weapon doesn't have an anim naturally, so use this one when in a BattleFortress

[FlakWeaponE]		; This belongs to Flak Cannon
Damage=35
ROF=20
Range=10
Projectile=FlakProj	; AA bullet shared with Flak Track
Speed=100
Report=FlakCannonAttack
Warhead=FlakWH
Anim=GUNFIRE
Burst=2

[FlakTrackAAGunE]	; Separate from Flak Cannon weapon so that stats may be tweaked
Damage=20
ROF=25
Range=8
Projectile=FlakProj	; AA bullet shared with Flak Cannon
Speed=100
Report=FlakTrackAttackAir
Warhead=FlakWH
Anim=GUNFIRE
Burst=2

[FlakTrackGunE]		; Anti-surface gun
Damage=25
ROF=25
Range=5
Projectile=FlakTProj
Speed=50
Report=FlakTrackAttackGround		; put in new sound for this
Warhead=FlakTWH
Anim=GUNFIRE
Burst=2

[FlakGuyGunE]		; Anti-surface gun for the Flak Trooper
Damage=20
ROF=20
Range=5
Projectile=FlakTProj
Speed=50
Report=FlakTrackAttackGround		; put in new sound for this
Warhead=FlakTWH
Anim=GUNFIRE
Burst=2

[FlakGuyAAGunE]	; Separate from Flak Cannon weapon so that stats may be tweaked
Damage=8
ROF=25
Range=8
Projectile=FlakProj	; AA bullet shared with Flak Cannon
Speed=100
Report=FlakTrackAttackAir
Warhead=FlakGuyWH
Anim=GUNFIRE
Burst=2

[DiskLaserE]
Damage=90
ROF=80
Range=7
Projectile=InvisibleAll
Speed=40
Report=FloatingDiscAttack
Warhead=DiskWH
Bright=yes
;IsHouseColor=true
LaserInnerColor = 216,0,184
LaserOuterColor = 80,0,88
LaserOuterSpread= 0,0,0
LaserDuration = 15
;IsLaser=true	; this flag tells the game to use the special laser draw effect
DiskLaser=yes; new ring draw laser
OmniFire=yes

; light anti-armor cannon
[90mmE]
Damage=75;36
ROF=30;50
Range=5.75
Projectile=Cannon
Speed=40
Warhead=GRIZAPE
Report=LightTankAttack
Anim=VTMUZZLE
Bright=yes
Burst=2

; anti-armor weapon
[105mmE]
Damage=65
ROF=50
Range=5
Projectile=Cannon
Speed=40
Warhead=GRIZAPE
Report=GrizzlyTankAttack
Anim=VTMUZZLE
Bright=yes
Burst=2

; large anti-armor cannon (two shooter)
[120mmxE]
Damage=100
ROF=80
Range=5.75
Projectile=Cannon
Speed=40
Warhead=ApocAPE
Report=ApocalypseAttackGround
Anim=VTMUZZLE
Burst=4
Bright=yes

; large anti-armor cannon (single shooter)
[120mmE]
Damage=90
ROF=65
Range=5.75
Projectile=Cannon
Speed=40
Warhead=RHINAPE
Report=RhinoTankAttack
Anim=VTMUZZLE
Bright=yes
Burst=2

[20mmE]
Damage=25
ROF=5
Range=5
Projectile=Invisible3
Speed=100
Warhead=SSA
Report=RocketeerAttack


[155mmE]
Damage=60
ROF=110
Range=8
MinimumRange=0
Projectile=Ballistic
Speed=10
Warhead=ARTYHE
Report=DestroyerAttack
Anim=GUNFIRE
Lobber=no
Burst=2


[160mmE]
Damage=90
ROF=100
Range=12
MinimumRange=0
Projectile=Ballistic
Speed=10
Warhead=SCHOPWH
Report=SeigeChopperAttackDeployed
Anim=GUNFIRE
Lobber=no
Burst=2

[TankBoltE]
Damage=150
ROF=60 ;changed on 11/29 from 50 to 60
Range=6
Speed=100
Warhead=Electric
Report=TeslaTankAttack
Projectile=Electricbounce
IsElectricBolt=true

; Fire by Telsa Trooper
[ElectricBoltE]
Damage=50
ROF=40
Range=5
Speed=100
Warhead=Shock
Report=TeslaTroopEliteAttack
Projectile=Electricbounce
IsElectricBolt=true
AssaultAnim=UCELEC;the anim to play when a UC building is cleared (assaulters need this on their primary weapon)

[ElectricFragment]
Damage=50
ROF=40
Range=5
Speed=100
Warhead=Shock
Report=TeslaTroopAttack
Projectile=Invisiblelow
IsElectricBolt=true
AssaultAnim=UCELEC;the anim to play when a UC building is cleared (assaulters need this on their primary weapon)


[SuperComet]
Damage=150
ROF=100
Range=10
Projectile=SuperCometP
Speed=10
Report=PrismTankAttack
Warhead=CometWH
Bright=yes
;LaserInnerColor = 216,0,184
;LaserOuterColor = 80,0,88
IsHouseColor=true
LaserOuterSpread= 0,0,0
LaserDuration = 15
IsLaser=true	; this flag tells the game to use the special laser draw effect

[SuperCometFragment]
Damage=50
ROF=100
Range=5
Projectile=SuperSmallCometP
Speed=10
Report=
Warhead=CometWH
Bright=yes
;LaserInnerColor = 216,0,184
;LaserOuterColor = 80,0,88
IsHouseColor=true
LaserOuterSpread= 0,0,0
LaserDuration = 15
IsLaser=true	; this flag tells the game to use the special laser draw effect

[MirageGunE]
Damage=150
ROF=80
Range=9
Projectile=InvisibleLow
Speed=100
Warhead=MirageWH
DisguiseFireOnly=no	; SJM: design change, tank can fire always
Report=MirageTankAttack
Bright=yes
DisguiseFakeBlinkTime=5 ; when a mirage fires, its disguise blinks for this long for VISUAL ONLY, not a logic blink
RevealOnFire=no ; Doesn't clear shroud when fired

[BlimpBombE]
Damage=250
Burst=1
ROF=50
Range=1.5
CellRangefinding=yes
Projectile=BlimpBombP
Speed=20
Warhead=KTSTLEXP
Report=KirovAttack
OmniFire=yes ; Don't need to turn even though I have no turret (Need since if I am directly over my target it will baffle the CloseEnough test for the facing)

; Fire by Brute
[PunchE]
Damage=100
ROF=60
Range=1.4
Speed=100
Warhead=Battering
Report=BruteSmashAttack
Projectile=InvisibleLow
;IsElectricBolt=true
;AssaultAnim=UCELEC;the anim to play when a UC building is cleared (assaulters need this on their primary weapon)
FireInTransport=no;can't fire out of the BattleFortress

; Tank smash by Brute
[SmashE]
Damage=100
ROF=60
Range=1.1
Speed=100
Warhead=Smashing
Report=BruteSmashAttack
Projectile=InvisibleLow
;IsElectricBolt=true
;AssaultAnim=UCELEC;the anim to play when a UC building is cleared (assaulters need this on their primary weapon)
FireInTransport=no;can't fire out of the BattleFortress

; Fire by Chrono Legion
[NeutronRifleE]
Damage=16
ROF=120
Range=5
Speed=100
Projectile=InvisibleLow
Warhead=ChronoBeam
Report=ChronoLegionAttack
IsRadBeam=yes

; Fire by Magnetron
[MagneticBeamE]
Damage=10000
ROF=20
Range=12
MinimumRange=3
Speed=100
Projectile=InvisibleHigh
Warhead=LocomotorBeam
Report=MagnetronAttack
IsMagBeam=yes

[MaverickE]
Damage=300
ROF=10
Range=9
Projectile=AirToGroundMissile ;GEF was AAHeatSeeker2 ; was HeatSeeker
Speed=70
Warhead=ORCAAP
Report=IntruderAttack
Burst=1;4

[Maverick2E]
Damage=400
ROF=10
Range=9
Projectile=AirToGroundMissile ;GEF was AAHeatSeeker2 ; was HeatSeeker
Speed=70
Warhead=ORCAAP
Report=BlackEagleAttack
Burst=1;2

[Maverick3E]
Damage=400
ROF=10
Range=9
Projectile=AirToGroundMissile ;GEF was AAHeatSeeker2 ; was HeatSeeker
Speed=70
Warhead=ORCAAP
Report=BlackEagleAttack
Burst=2

[HornetBombE]
Damage=80
ROF=3
Range=5
Projectile=NormalBomb
Speed=30
Warhead=ARTYHE
Report=HornetAttack

; Nighthawks gun
[BlackHawkCannonE]
Damage=40
ROF=40
Range=6
Projectile=QuadShell
Speed=100
Warhead=SSA
Report=BlackOpsAttack
Anim=MGUN-N,MGUN-NE,MGUN-E,MGUN-SE,MGUN-S,MGUN-SW,MGUN-W,MGUN-NW
OmniFire=yes
OmniFire.TurnToTarget=yes  ; boolean

[IvanBomberE]
Damage=600 ; Damage is used only for death explosion
ROF=50
Range=1.5 ; you can't change the target, but you can change yourself for CellRangefinding, so target could still be far side infantry
CellRangefinding=yes
FireOnce=yes ; Only fire once; don't stay in attack mission
Projectile=Invisible
Warhead=IvanBomb
;Report=CrazyIvanAttack
FireInTransport=no;can't fire out of the BattleFortress

; Fire by Desolater
[RadBeamWeaponE]
Damage=200
ROF=50
Range=8
Speed=100
Projectile=InvisibleLow
Warhead=RadBeamWarhead
IsRadBeam=yes
Report=DesolatorAttack

[SubTorpedoE]
Damage=100
ROF=120
Range=7
Projectile=Torpedo
Speed=18
Report=SubAttack
Warhead=APSplash
DecloakToFire=no
Burst=2

[BoomerTorpedoE]
Damage=60
ROF=120
Range=7
Projectile=Torpedo
Speed=18
Report=BoomerAttack2
Warhead=APSplash2
DecloakToFire=no
Burst=4


[SonicZapE]
Damage=8
AmbientDamage=15
ROF=80
Range=6
;Projectile=Null
Projectile=Sonic
Speed=100
Warhead=SonicWarhead
Report=DolphinAttack
IsSonic=Yes
;AntiUnderwater=yes
Burst=2
DecloakToFire=no

[HoverMissileE]
Damage=80
ROF=50
Range=6
Burst=4
Projectile=AAHeatSeeker2
Speed=40
Warhead=HE
Report=SeawolfAttack
MinimumRange=1

[MissileLauncherE]
Damage=50
ROF=20
Range=8
Burst=1
Projectile=AAHeatSeeker2	;AirToGroundMissile
Speed=40
Warhead=GUARDWH
Report=GuardianGIDeployedAttack
MinimumRange=1

;Hover Missile - AA only
[HoverMissile2e]
Damage=25
ROF=50
Range=10
Burst=2
Projectile=AAHeatSeeker
Speed=40
Warhead=AP
Report=SeawolfAttack
MinimumRange=1

[AWPE]
Damage=125
ROF=60
Range=14
Projectile=InvisibleLow
Speed=100
Report=SniperAttack
Warhead=HollowPoint
RevealOnFire=no ; Doesn't clear shroud when fired

[MP5E]
Damage=125
ROF=10
Range=6
Projectile=InvisibleLow
Speed=100
Warhead=HollowPoint
Report=SealAttack
AssaultAnim=UCBLOOD;the anim to play when a UC building is cleared (assaulters need this on their primary weapon)

[ChronoMP5E]
Damage=125
ROF=10
Range=6
Projectile=InvisibleLow
Speed=100
Warhead=HollowPointNoBuilding
Report=SealAttack

[ATGUNE]
Damage=65
ROF=50
Range=5
Projectile=Cannon
Speed=60
Warhead=RHINAPE
Report=TankDestroyerAttack
Anim=VTMUZZLE
Bright=yes
Burst=2

[SABOTE]
Damage=175
ROF=60
Range=6.75
Projectile=Cannon
Speed=60
Warhead=UltraAPE
Report=TankDestroyerAttack
Anim=VTMUZZLE
Bright=yes
Burst=2

[20mmRapidE]
Damage=50
ROF=50
Range=5.75
Projectile=Cannon
Speed=40
Warhead=HowitzerWH
Report=RhinoTankAttack
Anim=GUNFIRE
Bright=yes

[MindControlE]
Damage=10;Needed to be considered offensive unit
ROF=200
Range=14
Projectile=PsychicControl
Speed=100
Warhead=Controller
;Report=YuriMindControl
Anim=YURICNTL
FireOnce=yes


; Aegis missile
[MedusaE]
Damage=100
ROF=5
Range=14
Speed=150
Projectile=MedusaProjectile
Warhead=SAMWH
Report=AegisAttack
TurboBoost=yes
OmniFire=yes
Burst=2

[DoublePistolsE]
Damage=125
ROF=10
Range=8
Projectile=InvisibleLow
Speed=100
Warhead=HollowPoint2
Report=TanyaAttack
AssaultAnim=UCBLOOD;the anim to play when a UC building is cleared (assaulters need this on their primary weapon)

[AKME]
Damage=90
ROF=20
Range=9
Projectile=InvisibleLow
Speed=100
Warhead=BORISWH
Report=BorisAttack
AssaultAnim=UCBLOOD;the anim to play when a UC building is cleared (assaulters need this on their primary weapon)

; Squid wants some boat lovin'
[SquidGrabE]
Damage=40
ROF=99	; SJM: This is now ignored.  Damage frequency handled by special Squid code.
Range=1.5
CellRangefinding=yes
Projectile=SQDJUMP
Speed=30
DecloakToFire=no
Warhead=ParasitePlus ; Plus paralysis
LimboLaunch=yes ; Limbo shooter at launch (one shot or become the bullet)
Report=SquidAttack
Anim=SQDG_N,SQDG_NE,SQDG_E,SQDG_SE,SQDG_S,SQDG_SW,SQDG_W,SQDG_NW ; order matches 0=N & CW


; Squid attacking non boat
[SquidPunchE]
Damage=200
ROF=32 ;hard 16*2 until unit sprites get more complicated
Range=1.83
Projectile=InvisibleAll
Speed=30
Warhead=HE
;AntiOrganic=yes
Report=SquidAttackNonShip

[M60E]
Damage=25
ROF=20
Range=4
Projectile=InvisibleLow
Speed=100
Warhead=SA
Report=GIAttack
Anim=MGUN-N,MGUN-NE,MGUN-E,MGUN-SE,MGUN-S,MGUN-SW,MGUN-W,MGUN-NW
OccupantAnim=UCFLASH

;This was changed to be different from RA2.  - DB
[ParaE]
Damage=25
ROF=15
Range=6
Projectile=InvisibleLow
Speed=100
Warhead=SSA
Report=GIAttackDeployed

