; Seperate section for Aircrafts. Injected into Rulesmd.

; ******* Aircraft Type List *******
; This lists all of the aircraft types in the game. Each aircraft
; type should have a matching section that specifies the data it
; requires.
[AircraftTypes]
1=APACHE
2=ORCA
3=HORNET
4=V3ROCKET
5=ASW
6=DMISL
7=PDPLANE
8=BEAG
9=CARGOPLANE
10=BPLN
11=SPYP
12=CMISL

; **************************************************************************
; **************************************************************************
; **************************** Aircraft Types ******************************
; **************************************************************************
; **************************************************************************

;GEF I'm sick of having to hunt and peck through rules.ini. I'm going
;to make it more organized!

; **************************************************************************
; *************************** Allied Aircraft ******************************
; **************************************************************************



; Intruder ;Harrier
[ORCA]
UIName=Name:ORCA
Name=Intruder
Image=FALC
Prerequisite=RADAR
Primary=Maverick
CanPassiveAquire=no ; Won't try to pick up own targets
CanRetaliate=no; Won't fire back when hit
Strength=150
Category=AirPower
Armor=light
TechLevel=3
Sight=8
RadarInvisible=no
Landable=yes
MoveToShroud=yes
;Dock=GAAIRC,GAHPAD,NAHPAD
Dock=GAAIRC,AMRADR
PipScale=Ammo
Speed=14
;PitchSpeed=0.9
;PitchAngle=0

PitchSpeed=1.1
PitchAngle=0
OmniFire=yes

Owner=British,French,Germans,Americans
ForbiddenHouses=Alliance

Cost=1200
Points=20
ROT=3
Ammo=1
Crewed=yes
ConsideredAircraft=yes
AirportBound=yes ; If I ever need to land and there are no airports I crash because I can only land on them
GuardRange=30
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=3
IsSelectableCombatant=yes
VoiceSelect=IntruderSelect
VoiceMove=IntruderMove
VoiceAttack=IntruderAttackCommand
VoiceCrashing=IntruderVoiceDie
DieSound=
MoveSound=IntruderMoveLoop
CrashingSound=IntruderDie
ImpactLandSound=GenAircraftCrash
Locomotor={4A582746-9839-11d1-B709-00A024DDAFD1}
MovementZone=Fly
ThreatPosed=20	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
AuxSound1=IntruderTakeOff	;Taking off
AuxSound2=IntruderLanding	;Landing
VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
EliteAbilities=STRONGER,FIREPOWER,ROF
Fighter=yes
AllowedToStartInMultiplayer=no
ImmuneToPsionics=yes
ElitePrimary=MaverickE
PreventAttackMove=yes

; Destroyer's helicopter
[ASW]
UIName=Name:ASW
Name=Osprey
Primary=ASWBomb
Secondary=ASWCollision
NavalTargeting=2
LandTargeting=1
Strength=30
Category=AirPower
Armor=light
Spawned=yes
TechLevel=-1
Sight=2
RadarInvisible=no
Landable=yes
MoveToShroud=yes
;Dock=GAAIRC,AMRADR
PipScale=Ammo
Speed=12
PitchSpeed=.9
PitchAngle=0
Owner=British,French,Germans,Americans,Alliance
Cost=50
Points=10
ROT=5;3
Ammo=1
Crewed=no
GuardRange=30
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=2
VoiceSelect=
VoiceMove=
VoiceAttack=
VoiceFeedback=
DieSound=
CrashingSound=OspreyDie
ImpactLandSound=GenAircraftCrash
Locomotor={4A582746-9839-11d1-B709-00A024DDAFD1}
MovementZone=Fly
MovementRestrictedTo=Water ; See if this will affect landing only
ThreatPosed=10	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
AuxSound1=OspreyTakeOff ;Taking off
AuxSound2=OspreyLanding ;Landing
ImmuneToPsionics=yes
;Selectable=no	; SJM: this should be here but is commented out because bug prevents aircraft from landing

; Carrier Fighter
[HORNET]
UIName=Name:HORNET
Name=Hornet
Primary=HornetBomb
Secondary=HornetCollision
Strength=75
Category=AirPower
Armor=light
Spawned=yes
TechLevel=-1
Sight=2
RadarInvisible=no
Landable=yes
MoveToShroud=yes
;Dock=NAHPAD,GAHPAD
;Dock=GAAIRC,AMRADR
PipScale=Ammo
Speed=12
PitchSpeed=.9
PitchAngle=0
Owner=British,French,Germans,Americans,Alliance
Cost=50
Points=20
ROT=3
Ammo=1
Crewed=no
GuardRange=30
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=2
VoiceSelect=
VoiceMove=
VoiceAttack=
VoiceFeedback=
DieSound=
CrashingSound=HornetDie
ImpactLandSound=GenAircraftCrash
Locomotor={4A582746-9839-11d1-B709-00A024DDAFD1}
MovementZone=Fly
MovementRestrictedTo=Water ; See if this will affect landing only
ThreatPosed=10	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
AuxSound1=HornetTakeoff ;Taking off
AuxSound2=HornetLanding ;Landing
ImmuneToPsionics=yes
VeteranAbilities=STRONGER,FIREPOWER
EliteAbilities=STRONGER,FIREPOWER
;Selectable=no	; SJM: this should be here but is commented out because bug prevents aircraft from landing
ElitePrimary=HornetBombE


; **************************** Side Specific *******************************

; Black Eagle
[BEAG]
UIName=Name:BEAGLE
Name=Black Eagle
Prerequisite=RADAR
Primary=Maverick2
CanPassiveAquire=no ; Won't try to pick up own targets
CanRetaliate=no; Won't fire back when hit
Strength=200
Category=AirPower
Armor=light
TechLevel=3
Sight=8
RadarInvisible=no
Landable=yes
MoveToShroud=yes
Dock=GAAIRC,AMRADR
PipScale=Ammo
Speed=14
PitchSpeed=1.1
PitchAngle=0
OmniFire=yes
Owner=British,French,Germans,Americans,Alliance
RequiredHouses=Alliance
Cost=1200
Points=20
ROT=3
Ammo=1
Crewed=yes
ConsideredAircraft=yes
AirportBound=yes ; If I ever need to land and there are no airports I crash because I can only land on them
GuardRange=30
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=3
IsSelectableCombatant=yes
VoiceSelect=BlackEagleSelect
VoiceMove=BlackEagleMove
VoiceAttack=BlackEagleAttackCommand
VoiceCrashing=BlackEagleVoiceDie
DieSound=
MoveSound=BlackEagleMoveLoop
CrashingSound=BlackEagleDie
ImpactLandSound=GenAircraftCrash
Locomotor={4A582746-9839-11d1-B709-00A024DDAFD1}
MovementZone=Fly
ThreatPosed=20	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
;AuxSound1=BlackEagleTakeOff	;Taking off
;AuxSound2=BlackEagleLanding	;Landing
VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
EliteAbilities=STRONGER,FIREPOWER,ROF
Fighter=yes
AllowedToStartInMultiplayer=no
ImmuneToPsionics=yes
ElitePrimary=Maverick2E
PreventAttackMove=yes



; **************************************************************************
; *************************** Soviet Aircraft ******************************
; **************************************************************************

; Hind Transport. Unused.
[HIND]
UIName=Name:HIND
Name=Hind Transport
Prerequisite=NAWEAP
Primary=BlackHawkCannon
Strength=300
Category=AirPower
JumpJet=yes
Armor=light
TechLevel=-1
Sight=7
RadarInvisible=yes
Carryall=yes
Landable=yes
PipScale=Passengers
Passengers=10
Speed=15
PitchSpeed=1.1
JumpjetSpeed=40 ;params not defined use defaults (old globals way up top)
JumpjetClimb=50
JumpjetCrash=60 ; Climb, but down
JumpJetAccel=12
JumpJetTurnRate=12
JumpjetHeight=500
JumpjetWobbles=.01
JumpjetDeviation=1
Owner=Russians,Confederation,Africans,Arabs
RequiredHouses=Confederation
Cost=1000
Points=15
ROT=10
Crewed=yes
ConsideredAircraft=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=3
VoiceSelect=GenSovVehicleSelect
VoiceMove=GenSovVehicleMove
VoiceAttack=GenSovVehicleAttackCommand
DieSound=
CrashingSound=GenVehicleDie
ImpactLandSound=GenAircraftCrash
;Locomotor={4A582746-9839-11d1-B709-00A024DDAFD1} ;flying
Locomotor={92612C46-F71F-11d1-AC9F-006008055BB5} ;jumpjet
MovementZone=Fly
DamageParticleSystems=SparkSys,SmallGreySSys
AuxSound1=Dummy	;Taking off
AuxSound2=Dummy	;Landing
ThreatPosed=0
SpecialThreatValue=1
;Bombable=no
VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
Size=15
SizeLimit=2
HoverAttack=yes
;OmniFire=yes ;GEF moved to weapon
AllowedToStartInMultiplayer=no
Crashable=yes
SpeedType=Hover
PreventAttackMove=yes


; Soviet MIG
[BPLN]
UIName=Name:BPLN
Name=Soviet MIG
;Image=FORTRESS;PDPLANE
Strength=200
Category=AirLift
Armor=light
TechLevel=-1
Primary=Maverick3
;Primary=ParaDropWeapon	; Doesn't really fire it; dummy weapon
Spawned=yes	; Created by another object and therefore not player controllable
LeadershipRating=10
Selectable=no
RadarInvisible=no
Sight=0
Landable=no
MoveToShroud=yes
PitchAngle=0 ; default is 20 degrees
Speed=16; 18
Owner=British,French,Germans,Americans,Alliance,Russians,Confederation,Africans,Arabs,YuriCountry
Points=30
ROT=2
Crewed=yes
Ammo=1
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=2
Locomotor={4A582746-9839-11d1-B709-00A024DDAFD1}
MovementZone=Fly
ThreatPosed=0	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
ImmuneToPsionics=yes
CanPassiveAquire=no ; Won't try to pick up own targets
CanRetaliate=no; Won't fire back when hit
MoveSound=MigMoveLoop
DieSound=
VoiceCrashing=MigVoiceDie
CrashingSound=IntruderDie
ImpactLandSound=GenAircraftCrash
Fighter=yes
ElitePrimary=Maverick3E
Trainable=no
DeathWeapon=BlimpBomb
DeathWeaponDamageModifier=.1;gs needs a death weapon or it will do one laser blast's worth of crash damage.  This gives control
FlyBy=true	;GEF Don't slow down over your target


; Soviet Spy Plane
[SPYP]
UIName=Name:SpyP
Name=Soviet Spy Plane
;Image=PDPLANE
Strength=600
Category=AirLift
Armor=light
TechLevel=-1
Primary=SpyCameraWeapon
Spawned=yes	; Created by another object and therefore not player controllable
LeadershipRating=10
Selectable=no
RadarInvisible=no
Sight=0
Landable=no
MoveToShroud=yes
PitchAngle=0 ; default is 20 degrees
Speed=15
Owner=British,French,Germans,Americans,Alliance,Russians,Confederation,Africans,Arabs,YuriCountry
Points=30
ROT=2
Crewed=yes
Ammo=100
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=2
Locomotor={4A582746-9839-11d1-B709-00A024DDAFD1}
MovementZone=Fly
ThreatPosed=0	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
ImmuneToPsionics=yes
CanPassiveAquire=no ; Won't try to pick up own targets
CanRetaliate=no; Won't fire back when hit
MoveSound=SpyPlaneMoveLoop
DieSound=
CrashingSound=SpyPlaneDie
ImpactLandSound=GenAircraftCrash
DeathWeapon=BlimpBomb
DeathWeaponDamageModifier=.1;gs needs a death weapon or it will do nothing when it crashes since its weapon is a camera
FlyBy=true	;GEF Don't slow down over your target

; V3 Rocket -- warhead invoked from code.  No weapons attached here.
; missile stats and properties were previously invoked from their respective code in [General] section
; Now it is independant from [General] section, using Ares custom missile
[V3ROCKET]
UIName=Name:V3ROCKET
Name=V3 Rocket
FireAngle=1
Strength=50
Category=AirPower
Armor=special_2
Spawned=yes
MissileSpawn=yes
TechLevel=-1
Sight=1
RadarInvisible=no
Landable=yes
MoveToShroud=yes
Ammo=1 ;Aircraft are hard wired to require ammo
Speed=15
Owner=Russians,Confederation,Africans,Arabs
Cost=50
Points=20
ROT=3
Crewed=no
Explodes=no
GuardRange=30
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=2
Locomotor={B7B49766-E576-11d3-9BD9-00104B972FE8}
MovementZone=Fly
ThreatPosed=10	; This value MUST be 0 for all building addons
DamageParticleSystems=SmallGreySSys	; Sparks don't work well here.  SJM
AuxSound1=V3Attack ;Taking off
;AuxSound2=DROPDWN1 ;Landing
ImmuneToPsionics=yes
;VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
;EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
NoShadow=yes
Selectable=no
Trainable=no
DontScore=yes

;**** ARES SECTION ****

Missile.Custom=yes

; V3 Rocket control, powered by Ares

; V3 Rocket Custom Missile Setting
Missile.PauseFrames=0    ; How many frames the rocket pauses on the launcher before tilting
Missile.TiltFrames=60    ; How many frames it takes for the V3 rocket to tilt to firing position
Missile.PitchInitial=0.21; Starting pitch of the rocket before tilting up (0 is horizontal, 1 is vertical)
Missile.PitchFinal=0.5   ; Ending pitch of the rocket after tilting up; now it fires
Missile.TurnRate=0.05    ; Pitch maneuverability of rocket in air.  Adjust by trial and error.
Missile.RaiseRate=1		;GEF How much the missile will raise each turn on the launcher (for Cruise Missile only)
Missile.Acceleration=0.4 ; This much is added to the rocket's velocity each frame during launch
Missile.Altitude=768     ; Cruising altitude in leptons: at this height rocket BEGINS leveling off
Missile.BodyLength=256   ; The body of the rocket is this many leptons long
Missile.LazyCurve=yes    ; The rocket's path is a big, lazy curve.  V3 yes.  DMisl no.
; V3 Rocket Damage
Missile.Damage=200       ; Exploding V3 does this much damage (at center of explosion, presumably).
Missile.EliteDamage=400       ; Exploding V3 does this much damage (at center of explosion, presumably).
; V3 Rocket Warhead
Missile.Warhead=V3WH       ; this is the warhead on a V3 Rocket
Missile.EliteWarhead=V3EWH       ; this is the warhead on a V3 Rocket when the launcher is elite

; Dreadnought's Missile -- warhead invoked from code.  No weapons attached here.
; missile stats and properties were previously invoked from their respective code in [General] section
; Now it is independant from [General] section, using Ares custom missile
[DMISL]
UIName=Name:DMISL
Name=Dread Missile
FireAngle=1
Strength=50
Category=AirPower
Armor=special_2
Spawned=yes
MissileSpawn=yes
TechLevel=-1
Sight=0
RadarInvisible=no
Landable=yes
MoveToShroud=yes
Ammo=1 ;Aircraft are hard wired to require ammo
Speed=18;20
Owner=Russians,Confederation,Africans,Arabs
Cost=50
Points=20
ROT=4
Crewed=no
Explodes=no
GuardRange=30
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=2
Locomotor={B7B49766-E576-11d3-9BD9-00104B972FE8}
MovementZone=Fly
ThreatPosed=10	; This value MUST be 0 for all building addons
DamageParticleSystems=SmallGreySSys	; Sparks don't work well here.  SJM
AuxSound1=DreadnoughtAttack ;Taking off
;AuxSound2=DROPDWN1 ;Landing
ImmuneToPsionics=yes
;VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
;EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
NoShadow=yes
Selectable=no
Trainable=no
FlyBack=true
DontScore=yes

;**** ARES SECTION ****

Missile.Custom=yes

; Dread Missile control, powered by Ares

; Dread Missile Custom Setting
Missile.PauseFrames=20   ; How many frames the rocket pauses on the launcher before tilting
Missile.TiltFrames=60    ; How many frames it takes for the missile to tilt to firing position
Missile.PitchInitial=0   ; Starting pitch of the missile before tilting up (0 is horizontal, 1 is vertical)
Missile.PitchFinal=0.5   ; Ending pitch of the missile after tilting up; now it fires
Missile.TurnRate=0.08    ; Pitch maneuverability of missile in air.  Adjust by trial and error.
Missile.RaiseRate=1		;GEF How much the missile will raise each turn on the launcher (for Cruise Missile only)
Missile.Acceleration=0.8 ; This much is added to the missile's velocity each frame during launch
Missile.Altitude=768     ; Cruising altitude in leptons: at this height missile BEGINS leveling off
Missile.BodyLength=128   ; The body of the rocket is this many leptons long
Missile.LazyCurve=no     ; The rocket's path is a big, lazy curve.  V3 yes.  DMisl no.
; Dread Missile Damage
Missile.Damage=300       ; Exploding DMisl does this much damage (at center of explosion, presumably).
Missile.EliteDamage=600       ; Exploding DMisl does this much damage (at center of explosion, presumably).
; Dread Missile Warhead
Missile.Warhead=DMISLWH       ; this is the warhead on a DredMissile
Missile.EliteWarhead=DMISLEWH       ; this is the warhead on a DredMissile when the launcher is elite

; Cruise Missile -- warhead invoked from code.  No weapons attached here.
; missile stats and properties were previously invoked from their respective code in [General] section
; Now it is independant from [General] section, using Ares custom missile
[CMISL]
;UIName=Name:Missile.
UIName=Name:DMISL
Name=Cruise Missile
Image=BSUBMISL
FireAngle=1
Strength=50
Category=AirPower
Armor=special_2
Spawned=yes
MissileSpawn=yes
TechLevel=-1
Sight=0
RadarInvisible=no
Landable=yes
MoveToShroud=yes
Ammo=1 ;Aircraft are hard wired to require ammo
Speed=20
Owner=YuriCountry
Cost=50
Points=18;20
ROT=4
Crewed=no
Explodes=no
GuardRange=30
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=2
Locomotor={B7B49766-E576-11d3-9BD9-00104B972FE8}
MovementZone=Fly
ThreatPosed=10	; This value MUST be 0 for all building addons
DamageParticleSystems=SmallGreySSys	; Sparks don't work well here.  SJM
AuxSound1=BoomerAttack1
;AuxSound2=DROPDWN1 ;Landing
ImmuneToPsionics=yes
;VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
;EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
NoShadow=yes
Selectable=no
Trainable=no
FlyBack=true
DontScore=yes

;**** ARES SECTION ****

Missile.Custom=yes

; Cruise Missile control, powered by Ares

; Cruise Missile Custom Setting
Missile.PauseFrames=20   ; How many frames the rocket pauses on the launcher before tilting
Missile.TiltFrames=100    ; How many frames it takes for the missile to tilt (or lift) to firing position
Missile.PitchInitial=1   ; Starting pitch of the missile before tilting up (0 is horizontal, 1 is vertical)
Missile.PitchFinal=1.0   ; Ending pitch of the missile after tilting up; now it fires
Missile.TurnRate=0.10    ; Pitch maneuverability of missile in air.  Adjust by trial and error.
Missile.RaiseRate=1		;GEF How much the missile will raise each turn on the launcher (for Cruise Missile only)
Missile.Acceleration=1.0 ; This much is added to the missile's velocity each frame during launch
Missile.Altitude=768     ; Cruising altitude in leptons: at this height missile BEGINS leveling off
Missile.BodyLength=128   ; The body of the rocket is this many leptons long
Missile.LazyCurve=no     ; The rocket's path is a big, lazy curve.  V3 yes.  DMisl no. Missile. no.
; Cruise Missile Warhead
Missile.Damage=200       ; Exploding Missile. does this much damage (at center of explosion, presumably).
Missile.EliteDamage=250       ; Exploding Missile. does this much damage (at center of explosion, presumably).
; Cruise Missile Damage
Missile.Warhead=Missile.WH ; this is the warhead on a DredMissile
Missile.EliteWarhead=Missile.EWH ; this is the warhead on a DredMissile when the launcher is elite

; **************************************************************************
; **************************** Yuri Aircraft *******************************
; **************************************************************************

